name: Python CI

#trigger the workflow on push to the main branch or pull request
on:                                                        # This workflow is triggered ON push or pull request to the main branch
    push:                                                  #events that trigger the workflow (push, pull, merge, delete, etc. that trigger workflow)
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest                              #container to run the job. we also have windows-latest and macos-latest
        
        steps:
            #step 1: checkout the code from the repository
            - name: Checkout code
              uses: actions/checkout@v2                    #prebuilt action to checkout the code from the repository

            #step 2: set up the Python environment, install dependencies, and run tests
            # We are using Python 3.8, but you can change it to any version
            - name: Set up Python
              uses: actions/setup-python@v2                #prebuilt action to set up the Python environment #github action to set up the Python environment
              with:
                  python-version: '3.8' 
            
            #step 3: install dependencies and run tests
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            
            #step 4: run the tests
            - name: Run tests
              run: pytest                                  #run the tests using pytest
